"""revision

Revision ID: 13d5aa48d12c
Revises: b970f94d0c48
Create Date: 2023-03-29 13:38:24.554213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d5aa48d12c'
down_revision = 'b970f94d0c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(), nullable=True),
    sa.Column('ingredient_description', sa.String(), nullable=True),
    sa.Column('ingredient_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_table('product_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('directions', sa.Text(), nullable=True))
        batch_op.drop_column('brand')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('directions')

    op.drop_table('product_ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
