"""new database

Revision ID: d2f850d08015
Revises: 13d5aa48d12c
Create Date: 2023-03-29 15:55:54.738170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f850d08015'
down_revision = '13d5aa48d12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order_items')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('address')
        batch_op.drop_column('state')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_address', sa.String(), nullable=True))
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.FLOAT(), nullable=True))
        batch_op.drop_column('order_address')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=255), nullable=True))

    op.create_table('order_items',
    sa.Column('order_item_id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.drop_table('order_products')
    # ### end Alembic commands ###
